#!/bin/bash

# Simple script to demonstrate the C# to JVM compiler workflow

echo "=== C# to JVM Bytecode Compiler Demo ==="
echo

# Test 1: HelloWorld
echo "1. Compiling HelloWorld.cs..."
dotnet run --project CSharpJvmCompiler examples/HelloWorld.cs
echo
echo "Generated bytecode (HelloWorld.j):"
cat examples/HelloWorld.j
echo
echo "---"
echo

# Test 2: MathDemo
echo "2. Compiling MathDemo.cs..."
dotnet run --project CSharpJvmCompiler examples/MathDemo.cs
echo
echo "Generated bytecode (MathDemo.j):"
cat examples/MathDemo.j
echo
echo "---"
echo

# Test 3: SimpleReturn
echo "3. Compiling SimpleReturn.cs..."
dotnet run --project CSharpJvmCompiler examples/SimpleReturn.cs
echo
echo "Generated bytecode (SimpleReturn.j):"
cat examples/SimpleReturn.j
echo
echo "---"
echo

echo "=== Demo Complete ==="
echo
echo "The compiler successfully translated C# source code to JVM bytecode!"
echo "The .j files contain Jasmin assembly format which can be assembled"
echo "into .class files and executed on any JVM."
