using CSharpJvmCompiler;

class Program
{
    static void Main(string[] args)
    {
        if (args.Length == 0)
        {
            Console.WriteLine("C# to JVM Bytecode Compiler");
            Console.WriteLine("Usage: CSharpJvmCompiler <input.cs> [output.j]");
            Console.WriteLine();
            Console.WriteLine("This compiler translates C# source code into JVM bytecode.");
            Console.WriteLine("The output is in Jasmin assembly format (.j file).");
            return;
        }

        string inputFile = args[0];
        string outputFile = args.Length > 1 ? args[1] : Path.ChangeExtension(inputFile, ".j");

        try
        {
            // Read source code
            string sourceCode = File.ReadAllText(inputFile);
            Console.WriteLine($"Compiling {inputFile}...");

            // Lexical analysis
            var lexer = new Lexer(sourceCode);
            var tokens = lexer.Tokenize();
            Console.WriteLine($"Lexer: Found {tokens.Count} tokens");

            // Parsing
            var parser = new Parser(tokens);
            var ast = parser.Parse();
            Console.WriteLine($"Parser: Built AST with {ast.Classes.Count} class(es)");

            // Code generation
            var className = Path.GetFileNameWithoutExtension(inputFile);
            var generator = new JvmBytecodeGenerator(ast);
            var bytecode = generator.GenerateClassFile(className);

            // Write output
            File.WriteAllText(outputFile, bytecode);
            Console.WriteLine($"Generated JVM bytecode: {outputFile}");
            Console.WriteLine();
            Console.WriteLine("Compilation successful!");
            Console.WriteLine();
            Console.WriteLine("To run the generated bytecode:");
            Console.WriteLine($"1. Assemble with Jasmin: jasmin {outputFile}");
            Console.WriteLine($"2. Run with Java: java {className}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Compilation error: {ex.Message}");
            Environment.Exit(1);
        }
    }
}
